<a href="https://colab.research.google.com/github/Lucjusz44/My-Math/blob/main/Notebooks_EN/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mathematics

Exercises 2024/2025

## 1. Basic Operations on Matrices

For follwing matrices

$$
\mathbf{A}=
\begin{pmatrix}
1 & 2 \\
3 & 4
\end{pmatrix}
\qquad
\mathbf{B}=
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
\quad
\mathbf{C}=
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
\qquad
\mathbf{D}=
\begin{pmatrix}
-1 & 2 & 3 \\
4 & 0 & 6
\end{pmatrix}
\qquad
\mathbf{E}=
\begin{pmatrix}
1 & 2\\
4 & 5\\
7 & 8
\end{pmatrix}
$$

1.  Calculate: $\mathbf{A}+\mathbf{B}$; $\mathbf{B}-\mathbf{A}$;
    $\mathbf{A}+\mathbf{C}$; $\mathbf{D}+\mathbf{E}$.

2.  Calculate $\frac{1}{2}\mathbf{A}$, $2\mathbf{B}$, $-3\mathbf{C}$,
    and $4\mathbf{D}$.

3.  Calculate the products $\mathbf{A}\cdot \mathbf{B}$;
    $\mathbf{B} \cdot \mathbf{A}$; $\mathbf{A} \cdot \mathbf{D}$;
    $\mathbf{D} \cdot \mathbf{E}$.

## 2. Determinants 2x2 and 3x3

Calculate the determinants for the 2x2 and 3x3 matrices given below.

2x2 Matrices:

$$
\mathbf{A} =
\begin{pmatrix}
2 & 3 \\
1 & 4
\end{pmatrix}
, \qquad
\mathbf{B} =
\begin{pmatrix}
5 & 6 \\
7 & 8
\end{pmatrix}
, \qquad
\mathbf{C} =
\begin{pmatrix}
-1 & 2 \\
3 & 0
\end{pmatrix}
$$

3x3 Matrices:

$$
\mathbf{D} =
\begin{pmatrix}
1 & 0 & 2 \\
-1 & 3 & 1 \\
2 & 4 & -2
\end{pmatrix}
, \qquad
\mathbf{E} =
\begin{pmatrix}
3 & 1 & -1 \\
0 & 2 & 4 \\
5 & 3 & 2
\end{pmatrix}
, \qquad
\mathbf{F} =
\begin{pmatrix}
2 & -3 & 1 \\
1 & 4 & -2 \\
1 & 5 & 3
\end{pmatrix}
$$

## 3. Determinants using Laplace’s Expansion

Calculate the determinants of the following matrices:

$$
\mathbf{A} =
\begin{pmatrix}
2 & 3 & 1 \\
1 & 4 & 0 \\
3 & 2 & 1
\end{pmatrix}
,\qquad
\mathbf{B} =
\begin{pmatrix}
2 & 3 & 1 \\
1 & 4 & 0 \\
3 & 2 & 0  \\
\end{pmatrix}
,\qquad
\mathbf{C} =
\begin{pmatrix}
2 & 3 & 1 & 4 \\
1 & 0 & 0 & 6 \\
3 & 2 & 1 & 5 \\
2 & 1 & 4 & 0
\end{pmatrix}
,\qquad
\mathbf{D} =
\begin{pmatrix}
2 & 3 & 1 & 4 & 5 \\
1 & 4 & 0 & 0 & 7 \\
3 & 0 & 0 & 0 & 0 \\
2 & 1 & 4 & 3 & 2 \\
1 & 2 & 3 & 4 & 5
\end{pmatrix}
$$

## 4. Determinants from the Gauss Method and Triangular Matrices

Perform row and column operations to reduce the following matrices to an
upper triangular form and calculate their determinants by taking the
product of the diagonal elements.

$$
\mathbf{A} = \begin{pmatrix}
12 & 3 \\
-18 & -4
\end{pmatrix}\qquad\qquad
\mathbf{B} = \begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{pmatrix}
$$

## 5. Inverse of a Matrix from the formula

1.  Find the inverse matrix for matrix

$$\mathbf{A}=\begin{pmatrix}
2 & 0 & 1 \\
0 & 1 & 0 \\
1 & 2 & 0
\end{pmatrix}$$

and verify if the result is correct.

1.  Determine the rank of the matrix:

$$\mathbf{B} =
\begin{pmatrix}
4 & -3 & 7 \\
-1 & 6 & 3 \\
2 & 9 & 1
\end{pmatrix}$$

## 6. Inverse of a Matrix using the Gauss Method

Find the inverse matrices using the Gauss method:

$$
\mathbf{A} =
\begin{pmatrix}
1 & 2\\
3 & 4
\end{pmatrix}
, \qquad
\mathbf{B} =
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 1 \\
2 & 3 & 2
\end{pmatrix}
,\qquad
\mathbf{C} =
\begin{pmatrix}
0 & 0 & 1\\
0 & 1 & 0\\
1 & 0 & 0
\end{pmatrix}
$$

## 7. Linear Equations old school

Solve the following systems of equations without using matrices:

-   $3x-2y=5, \quad 2x+3y=7$,
-   $2x-3y=10, \quad 4x+5y=20$,
-   $2x - y + z = 3, \quad x + 2y - z = 1, \quad 3x - y + 2z = 11$.
-   $2x-3y+4z+2t=2, \quad 3x+2y-5z+3t=3, \quad 4x-3y+2z-5t=4, \quad 5x+4y-3z+2t=5$.

## 8. Linear equations by Cramer’s Rule

1.  Solve the system of equations:

$$\begin{cases}
   2x_1 - 3x_2 = 7\\
   3x_1 + 5x_2 = 2
\end{cases}$$

1.  Solve the system of equations:

$$\begin{cases}
   2x + y - z = 1 \\
   x - y + 2z = 4 \\
   3x - 2z = -1
\end{cases}$$

1.  Solve the system of equations:

$$\begin{cases}
   x + y + z - t = 2 \\
   x - z + 2t = 6 \\
   2x - 3y + t = 4 \\
   3x + y + 3z - 4t = -2
\end{cases}$$

1.  Why can’t the following system of equations be solved using Cramer’s
    rule?

$$\begin{cases}
x_1 + 2x_2 + 3x_3 = 3 \\
4x_1 + 5x_2 + 6x_3 = 2 \\
7x_1 + 8x_2 + 9x_3 = 1
\end{cases}$$

## 9. Linear equations by Gauss Elimination

$$\begin{cases}
x + 2y - 2z = 4 \\
2x + y + z = 0 \\
3x + 2y + z = 1
\end{cases}
\quad
\begin{cases}
x + y + z - t = 2 \\
2x + y + z = 3 \\
-x + z - t = 0 \\
3x + 2y - z + 2t = -1
\end{cases}
\quad
\begin{cases}
x + y - z - t = 0 \\
2x + 3y - 2z + t = 4 \\
3x + 5z = 0 \\
-x + y - 3z + 2t = 3
\end{cases}
$$

## 10. Linear equations by Matrix Inversion

1.  Solve the system of linear equations using the inverse matrix
    method:

$$
\begin{cases}
x + 2y + 3z = 5, \\
2y + 3z = 4, \\
3z = 3.
\end{cases}
$$

1.  Solve the system of linear equations using the inverse matrix
    method:

$$
\begin{cases}
x_1 + 2x_2 + 3x_3 = 41, \\
4x_1 + 5x_2 + 6x_3 = 93, \\
7x_1 + 8x_2 + 9x_3 = 145.
\end{cases}
$$

## 11. Vectors I

1.  By what number should vector $\mathbf{a} = [3, 4]$ be multiplied so
    that its length is equal to 1?

2.  Calculate the length of vector $\mathbf{b} = [1, 1]$ and find the
    unit vector of this vector.

3.  Plot the vector and the unit vector from the previous exercise.

4.  Calculate the length of vector $\mathbf{c} = [1, 2, 3]$ and find the
    unit vector of this vector.

5.  Find the Cartesian coordinates of vector $\mathbf{v} = [2, 3, 4]$ in
    the basis
    $\{\mathbf{b_1} = [1, 0, 1], \mathbf{b_2} = [0, 1, 0], \mathbf{b_3} = [1, 0, -1]\}$.

## 12. Vectors II

1.  Perform the addition of vector $[2, 1]$ to vector $[-1, 1]$. Plot
    both vectors and their sum on a graph.

2.  Calculate the area of the triangle spanned by vectors $[2, 1, 2]$
    and $[-1, 1,1]$.

3.  Calculate the volume of the parallelepiped spanned by vectors
    $[2, 1, -1]$, $[-1, 1, 0]$, and $[1, 2, 1]$.

4.  Check if vectors $[2, 1]$ and $[-1, 1]$ are perpendicular.

5.  Calculate the angle in degrees between vectors $[4,2,1]$ and
    $[1,3,2]$.

6.  For three-dimensional vectors: $\mathbf{a}=[a_x, a_y, a_z]$,
    $\mathbf{b}=[b_x, b_y, b_z]$, $\mathbf{c}=[c_x, c_y, c_z]$, prove
    that the following identity is satisfied:

$$
\mathbf{a} \times (\mathbf{b} \times \mathbf{c}) = (\mathbf{a} \cdot \mathbf{c}) \mathbf{b} - (\mathbf{a} \cdot \mathbf{b}) \mathbf{c}.
$$

## 13. Vectors III

1.  Divide the line segment connecting points $A(-1, 2)$ and $B(3, -2)$
    in the ratio $1:3$. Illustrate the result on a graph.

2.  Project vector $\mathbf{a} = (3, 4)$ onto the $OX$ and $OY$ axes.
    Illustrate the result on a graph.

3.  Project vector $\mathbf{a} = (2,3)$ onto vector
    $\mathbf{b} = (1, 1)$. Ilustrate the result on a graph.

4.  Project vector $\mathbf{b} = (1, 1)$ onto vector
    $\mathbf{a} = (2, 3)$. Ilustrate the result on a graph.

## 14. Equations of lines on a plane

-   The line passes through points $A(1, 2)$ and $B(3, 4)$. Find the
    equation of the line.
-   The line passes through point $A(1, 2)$ and is parallel to the line
    $y = 2x + 3$. Find the equation of the line.
-   The line passes through point $A(1, 2)$ and is perpendicular to the
    line $y = 2x + 3$. Find the equation of the line.
-   We have two lines $y = 2x + 3$ and $y = 3x + 2$. Find the
    intersection point of these lines and calculate the angle between
    them.
-   Write the equation of the line passing through point $A(1, 2)$ and
    parallel to the vector $\mathbf{v} = [2, 3]$.
-   We have the line $y = 2x + 3$. Find an example of a line
    perpendicular and parallel to it.
-   We have the line $y = 2x + 3$ and point $A(1, 2)$. Find the distance
    from point $A$ to the line.
-   The line intersects the coordinate axes at points $A(2, 0)$ and
    $B(0, 3)$. Find the equation of the line.
-   Calculate the angle between the line $y = x + 3$ and the $Ox$ axis.
-   Provide a vector perpendicular to the line $x + y + 1 = 0$.

## 15. Equations of second-order curves (conic sections)

-   Find the equation of a circle with center at point $A(1,2)$ and
    radius $r=3$.
-   Find the equation of a parabola intersecting the $Ox$ axis at points
    $x=2$, $x=4$, and passing through point $y(3)=1$.
-   Find the center of the ellipse with the equation
    $x^2 + 4y^2 - 4x - 16y + 16 = 0$.
-   Find the slope ($m>0$) of the line $y=mx-5$ that is tangent to the
    circle with the equation $x^2 + y^2=1$.
-   Find the intersection points of the hyperbola $x^2 - y^2 = 1$ with
    the ellipse’s line $x^2 + 4y^2 = 6$.
-   For the given hyperbola $x^2 - y^2 = 1$, find the distance between
    its branches.

## 16. Equations of planes in space

-   The plane passes through points $A(1, 2, 3)$, $B(3, 4, 5)$, and
    $C(2, 1, 4)$. Find the equation of the plane.
-   The plane passes through point $A(1, 2, 3)$ and is parallel to the
    plane $2x + 3y + 4z = 5$. Find the equation of the plane.
-   The plane passes through point $A(1, 2, 3)$ and is perpendicular to
    the normal vector $\mathbf{n} = [2, 3, 4]$. Find the equation of the
    plane.
-   We have two planes $2x + 3y + 4z = 5$ and $3x + 4y + 2z = 6$. Find
    the line of intersection of these planes.
-   Write the equation of the plane passing through point $A(1, 2, 3)$
    and parallel to vectors $\vec{v_1} = [1, 0, 1]$ and
    $\vec{v_2} = [0, 1, -1]$.
-   We have the plane $2x + 3y + 4z = 5$. Find an example of a plane
    parallel and perpendicular to it.
-   We have the plane $2x + 3y + 4z = 5$ and point $A(1, 2, 3)$. Find
    the distance from point $A$ to this plane.
-   The plane intersects the coordinate axes at points $A(2, 0, 0)$,
    $B(0, 3, 0)$, and $C(0, 0, 4)$. Find the equation of the plane.
-   Calculate the angle between the plane $x + y + z = 1$ and the plane
    $x = 0$ (i.e., the $yz$ plane).
-   Find the vector perpendicular to the plane $x + y + z = 1$.

## 17. Equations of second-order surfaces

-   Write the equation of a sphere with center at point $P=(1,2,3)$ and
    radius $r=3$.
-   Do the spheres with equations $x^2 + y^2 + z^2 = 1$ and
    $x^2 + y^2 + z^2 = 2$ have any common points?
-   What curve in space is formed by the intersection of the sphere
    $x^2 + y^2 + z^2 = 1$ with the sphere $(x-1)^2 + y^2 + z^2 = 1$?
    Find the equation of this curve.
-   Write the equation of the tangent plane to the paraboloid
    $z=(x-1)^2+y^2+1$ at point $P(1,0,1)$.

## 18. Functions

1.  Draw in a single Geogebra notebook the following functions:
    -   $f(x) = x^2$
    -   $g(x) = \sqrt{x}$
    -   $h(x) = \frac{1}{x}$
    -   $j(x) = \sin(x)$

Find value of all the above functions at $x = 2$.

1.  Let $f(x) = 3x - 1$ and $g(x) = \sqrt{x}$. Find:
    -   $f(g(x))$
    -   $g(f(x))$
    -   $f(f(x))$
    -   $g(g(x))$

and visualize functions in a single Geogebra notebook.

1.  Let $f(x) = e^x$ and $g(x) = \ln(x)$. Check: $f(g(x))$ and
    $g(f(x))$. What do you notice?

2.  We have function $f=\{(1,7), (2,9), (3,11)\}$. Give inverse function
    $f^{-1}$.

3.  We have function $f=\{(1,7), (2,7), (3,11)\}$. Give inverse function
    $f^{-1}$.

4.  We have function $f(x)= x-1$. Give inverse function $f^{-1}$. Show
    both functions on the same Geogebra notebook.

## 19. Limits of Sequences

1.  Calculate:
    -   $\displaystyle \lim_{n \to \infty} \frac{n^2 + 3n}{2 n^2 - 2n}$

    -   $\displaystyle \lim_{n \to \infty} \frac{(2n+3)^3}{n^3-1}$
2.  Prove using the squeeze theorem:
    -   $\displaystyle\lim_{n \to \infty} \frac{\sin(n)}{n}$
3.  Find the limit of the sequence:
    -   $a_n = (1+\frac{1}{n})^n$

## 20. Limits of Real Functions

1.  Compute:

    -   $\displaystyle\lim_{x \to \infty} \frac{x^3 + 2x^2}{x^4 - 3x^3}$

2.  Find:

    -   $\displaystyle \lim_{x \to 0} \frac{\sin(3x)}{2x+1}$.

3.  Find the asymptotes of the function:

    -   $f(x) = \frac{x^2 - 1}{x^2 + 1}$
    -   $g(x) = \frac{\sin(x)}{x^2+1}$

## 21. Derivatives

1.  Compute derivatives of functions:

    -   $y(x) = -3x+3$
    -   $y(x) = \pi x + \sin(1)$
    -   $y(x) = 4+\sin(2)$
    -   $y(x) = 2x^3 - 3x^2 + 8x - 9$
    -   $y(x) = 6 x^{1/3}$
    -   $y(x) = \sqrt{x}$
    -   $y(x) = \cos(x) + \sin(x)$
    -   $y(x) = 2\sin(x) \cos(x)$
    -   $y(x) = x\sin(x)$
    -   $y(x) = (x+1)(x+1)$
    -   $y(x) = \frac{x}{x+1}$
    -   $y(x) = (x+1)\exp(x)$
    -   $y(x) = \sin(x^2)$
    -   $y(x) = \exp(-2x)$
    -   $y(x) = \frac{1}{\sin(x+1)}$
    -   $y(x) = \sqrt{2x+1}$

2.  Prove:

    -   $\frac{d}{dx} (\ln(\sin(x))) = \cot(x)$

3.  For $f(x) = \cos(x)$, verify that $f''(x) = -f(x)$.

4.  Using de l’Hospital’s Rule, find the improper limits:

    -   $\displaystyle \lim_{x\to 0} \frac{\sin{x}}{x}$

    -   $\displaystyle \lim_{x\to \infty} \frac{\ln x}{x}$

    -   $\displaystyle \lim_{x\to \infty} \frac{\exp(x)}{x}$

5.  In physics, the position of a particle is given by
    $x(t) = 3t^2 - 6t + 1$. Find the velocity $V(t)=x'(t)$ and
    acceleration $a(t)=V'(t)=x''(t)$ of the particle at time $t = 2$.

## 22. Extremum

1.  The profit function is $P(u) = -2u^2 + 50u - 300$, where $u$ is the
    number of units sold. Find the number of units that maximize profit.

2.  You have 10 meters of string, and you need to use it to enclose the
    largest possible rectangular. Find the dimensions of the rectangle.

3.  Find extremum od $f(x) = x^2 + 3x - 5$.

4.  Find extremum of $f(x) =\frac{x^2+2x+1}{x-1}$.

## 23. Taylor Series

1.  Find the Taylor series and visualize obtained functions in Geogebra:
    -   $f(x) = \cos(x)$ around $x = 0$ up to the 4th degree.
    -   $h(x) = 1/(1-x)$ around $x = 0$ up to the 4rd degree.
    -   $g(x) = \sin(x)$ around $x = \pi$ up to the 4rd degree.
2.  Find a tangent line $y = f'(x_0) (x-x_0) + f(x_0)$ to the function
    $f(x) = e^{\sin(x)}$ at $x_0 = \pi$. Hints for Geogebra
    visualization: define f(x), include slider s, define y = f’(s)
    (x-s) + f(s), and include point P(s, f(s)).

## 24. Integrals

1.  Compute:

    -   $\int 1 dx$
    -   $\int (x^2 +2) dx$
    -   $\int 2\sin(x) dx$
    -   $\int \frac{3}{x} dx$
    -   $\int \frac{1}{x^2} dx$
    -   $\int \left( \frac{1}{3}x^4 - 5 \right) \, dx$
    -   $\int (\sin^2 x + \cos^2 x) \, dx$
    -   $\int (5 \sin x + 3e^x) \, dx$
    -   $\int \sqrt[3]{x} \, dx$
    -   $\int \sqrt{10x} \, dx$
    -   $\int \cos\left(\frac{5}{2}x + 3\right) \, dx$
    -   $\int \frac{\cos(\ln(x))}{x} \, dx$
    -   $\int x \ln(x) \, dx$
    -   $\int x e^x \, dx$

2.  Calculate integrals over the interval $[0, \pi]$ and visualize them
    in Geogebra:

    -   $f(x)=2x+1$
    -   $g(x)=x^2$

3.  Calculate the area of the region bounded by the lines: $x = 1$,
    $x = 2$, $y = 0$, and $y = x^2 + 1$. Show it in Geogebra.

4.  Calculate the area under the sine curve over the interval
    $[0, \pi]$, using:

$$P = \int_a^b f(x) \, dx = \int_0^\pi \sin(x) \, dx$$

1.  Calculate the length of the sine curve over the same interval using:

$$L = \int_a^b \sqrt{1 + (f'(x))^2} \, dx= \int_0^\pi \sqrt{1 + \cos^2(x)} \, dx
$$

1.  Find the distance of the moving particle between time $t=0$ and
    $t=2$ for the following position function: $x(t) = 3t^2 - 6t + 1$.

## 25. Differential Equations

1.  Solve the following first-order ordinary differential equations:

    -   $y'(x)= y$
    -   $y'(x) = \frac{1}{2y(x)}$

2.  Solve the first-order ordinary differential equations using the
    method of separation of variables for $x$ and $y=y(x)$:

    -   $\frac{dy}{dx} = \frac{x}{y}$
    -   $\frac{dy}{dx} = \frac{y}{x}$
    -   $\frac{dy}{dx} = xy$

3.  Solve the second-order ordinary differential equations:

    -   $y''(x) + y'(x) = 0$, with boundary conditions $y(0) = 2$ and
        $y'(0) = -1$

    -   $y''(x) - y(x)= 0$, with boundary conditions $y(0) = 2$ and
        $y'(0) = 0$

    -   $\frac{d^2\,y(x)}{dx^2} = -\omega^2 y(x)$.

4.  Check if the function $\psi(t, x) = A \cos(\omega t + kx)$ is a
    solution of the second-order partial differential equation (the
    so-called “wave equation”), where
    $v = \frac{\omega}{k} = \frac{2\pi / T}{2\pi / \lambda}$:

$$
\frac{\partial^2 \psi(t, x)}{\partial t^2} - v^2 \frac{\partial^2 \psi(t, x)}{\partial x^2} = 0.
$$

In [ ]:
#1
import numpy as np

# Define matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[-1, 2], [3, 0]])
D = np.array([[-1, 2, 3], [4, 0, 6]])
E = np.array([[1, 2], [4, 5], [7, 8]])

# 1. Calculate: A + B; B - A; A + C; D + E
print("A + B:")
print(A + B)
print("\nB - A:")
print(B - A)
print("\nA + C:")
print(A + C)
# D + E is not possible due to incompatible dimensions

# 2. Calculate 1/2A, 2B, -3C, and 4D
print("\n1/2A:")
print(0.5 * A)
print("\n2B:")
print(2 * B)
print("\n-3C:")
print(-3 * C)
print("\n4D:")
print(4 * D)

# 3. Calculate the products A⋅B; B⋅A; A⋅D; D⋅E
print("\nA⋅B:")
print(np.dot(A, B))
print("\nB⋅A:")
print(np.dot(B, A))
# A⋅D is not possible due to incompatible dimensions
print("\nD⋅E:")
print(np.dot(D, E))

A + B:
[[ 6  8]
 [10 12]]

B - A:
[[4 4]
 [4 4]]

A + C:
[[0 4]
 [6 4]]

1/2A:
[[0.5 1. ]
 [1.5 2. ]]

2B:
[[10 12]
 [14 16]]

-3C:
[[ 3 -6]
 [-9  0]]

4D:
[[-4  8 12]
 [16  0 24]]

A⋅B:
[[19 22]
 [43 50]]

B⋅A:
[[23 34]
 [31 46]]

D⋅E:
[[28 32]
 [46 56]]


In [ ]:
#2
import numpy as np

# Define matrices
A = np.array([[2, 3], [1, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[-1, 2], [3, 0]])
D = np.array([[1, 0, 2], [-1, 3, 1], [2, 4, -2]])
E = np.array([[3, 1, -1], [0, 2, 4], [5, 3, 2]])
F = np.array([[2, -3, 1], [1, 4, -2], [1, 5, 3]])

# Calculate determinants
print("Determinant of A:", np.linalg.det(A))
print("Determinant of B:", np.linalg.det(B))
print("Determinant of C:", np.linalg.det(C))
print("Determinant of D:", np.linalg.det(D))
print("Determinant of E:", np.linalg.det(E))
print("Determinant of F:", np.linalg.det(F))

Determinant of A: 5.000000000000001
Determinant of B: -2.000000000000005
Determinant of C: -6.0
Determinant of D: -29.99999999999999
Determinant of E: 5.999999999999995
Determinant of F: 60.000000000000036


In [ ]:
#3
import numpy as np

def laplace_expansion(matrix):
  """Calculates the determinant of a 3x3 matrix using Laplace's expansion."""
  if matrix.shape != (3, 3):
    raise ValueError("Input must be a 3x3 matrix.")

  det = (
      matrix[0, 0] * (matrix[1, 1] * matrix[2, 2] - matrix[1, 2] * matrix[2, 1])
      - matrix[0, 1] * (matrix[1, 0] * matrix[2, 2] - matrix[1, 2] * matrix[2, 0])
      + matrix[0, 2] * (matrix[1, 0] * matrix[2, 1] - matrix[1, 1] * matrix[2, 0])
  )
  return det

# Example usage:
A = np.array([[2, 3, 1], [1, 4, 0], [3, 2, 1]])
det_A = laplace_expansion(A)
print("Determinant of A using Laplace's expansion:", det_A)

Determinant of A using Laplace's expansion: -5


In [ ]:
#4
import numpy as np

def gauss_determinant(matrix):
  """Calculates the determinant of a 2x2 matrix using the Gauss method."""
  if matrix.shape != (2, 2):
    raise ValueError("Input must be a 2x2 matrix.")

  # Perform row operations (example: subtract a multiple of row 1 from row 2)
  factor = matrix[1, 0] / matrix[0, 0]
  matrix[1, :] = matrix[1, :] - factor * matrix[0, :]

  # Determinant is the product of diagonal elements
  det = matrix[0, 0] * matrix[1, 1]
  return det

# Example usage:
A = np.array([[12, 3], [-18, -4]])
det_A = gauss_determinant(A)
print("Determinant of A using Gauss method:", det_A)

Determinant of A using Gauss method: 0


In [ ]:
#5
import numpy as np

A = np.array([[2, 0, 1], [0, 1, 0], [1, 2, 0]])

# Calculate the inverse
A_inv = np.linalg.inv(A)
print("Inverse of A:")
print(A_inv)

# Verify the result (A * A_inv should be the identity matrix)
print("\nVerification (A * A_inv):")
print(np.dot(A, A_inv))

Inverse of A:
[[ 0. -2.  1.]
 [ 0.  1.  0.]
 [ 1.  4. -2.]]

Verification (A * A_inv):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#6
import numpy as np

def gauss_inverse(matrix):
  """Calculates the inverse of a 2x2 matrix using the Gauss method."""
  if matrix.shape != (2, 2):
    raise ValueError("Input must be a 2x2 matrix.")

  # Augment the matrix with the identity matrix
  augmented_matrix = np.concatenate([matrix, np.identity(2)], axis=1)

  # Perform row operations (example: swap rows, multiply a row by a scalar, etc.)
  # ... (Implement the necessary row operations to transform the left side into the identity) ...

  # The right side of the augmented matrix is now the inverse
  inverse = augmented_matrix[:, 2:]
  return inverse

# Example usage:
A = np.array([[1, 2], [3, 4]])
A_inv = gauss_inverse(A)
print("Inverse of A using Gauss method:")
print(A_inv)

Inverse of A using Gauss method:
[[1. 0.]
 [0. 1.]]


In [ ]:
#7
def solve_linear_equations(eq1, eq2):
  """Solves a system of two linear equations using substitution.

  Args:
      eq1: A tuple representing the first equation in the form (a, b, c) for ax + by = c.
      eq2: A tuple representing the second equation in the form (a, b, c) for ax + by = c.

  Returns:
      A tuple containing the solutions for x and y, or None if there is no unique solution.
  """

  a1, b1, c1 = eq1  # Coefficients of equation 1
  a2, b2, c2 = eq2  # Coefficients of equation 2

  # Check for special cases (inconsistent or dependent systems)
  if a1 == 0 and b1 == 0:
    if c1 != 0:  # Inconsistent system
      return None
    else:  # Dependent system (infinitely many solutions)
      return None
  if a2 == 0 and b2 == 0:
    if c2 != 0:  # Inconsistent system
      return None
    else:  # Dependent system (infinitely many solutions)
      return None

  # Check if equations are equivalent (infinite solutions)
  if a1 * b2 == a2 * b1 and a1 * c2 == a2 * c1 and b1 * c2 == b2 * c1:
    return None  # Infinite solutions

  # Solve for x and y using substitution (avoiding premature use of y)
  if a1 != 0:  # Solve eq1 for x
    # x = (c1 - b1 * y) / a1  # We won't use this directly to avoid 'y'
    # Substitute into eq2: a2 * x + b2 * y = c2
    # a2 * ((c1 - b1 * y) / a1) + b2 * y = c2
    # Solve for y:
    y = (a1 * c2 - a2 * c1) / (a1 * b2 - a2 * b1)
    # Substitute y back into eq1 to find x:
    x = (c1 - b1 * y) / a1
  elif b1 != 0:  # Solve eq1 for y (if a1 is 0)
    y = (c1 - a1 * x) / b1  # substitute it into the other equation
    x = (c2 - b2*y) / a2
    y = (c1 - a1 * x) / b1

  else:  # if a1 and b1 are both 0 and c1 is 0
      return None

  return x, y

# Example usage:
eq1 = (3, -2, 5)  # 3x - 2y = 5
eq2 = (2, 3, 7)  # 2x + 3y = 7
solution = solve_linear_equations(eq1, eq2)

if solution:
  x, y = solution
  print("Solution: x =", x, ", y =", y)
else:
  print("No unique solution exists for this system of equations.")

Solution: x = 2.230769230769231 , y = 0.8461538461538461


In [ ]:
#8
import numpy as np

def cramer_rule(A, b):
  """Solves a system of linear equations using Cramer's rule.

  Args:
    A: The coefficient matrix (NumPy array).
    b: The constant vector (NumPy array).

  Returns:
    A NumPy array containing the solutions, or None if no unique solution exists.
  """

  n = A.shape[0]  # Number of variables
  det_A = np.linalg.det(A)

  if det_A == 0:
    return None  # No unique solution (determinant is 0)

  solutions = []
  for i in range(n):
    # Create a matrix by replacing the i-th column of A with b
    Ai = A.copy()
    Ai[:, i] = b

    # Calculate the solution for the i-th variable
    xi = np.linalg.det(Ai) / det_A
    solutions.append(xi)

  return np.array(solutions)

# Example usage for a 2x2 system:
A = np.array([[2, -3], [3, 5]])
b = np.array([7, 2])
solution = cramer_rule(A, b)

if solution is not None:
  print("Solution for 2x2 system:", solution)
else:
  print("No unique solution for 2x2 system.")

# Example usage for a 3x3 system:
A = np.array([[2, 1, -1], [1, -1, 2], [3, 0, -2]])
b = np.array([1, 4, -1])
solution = cramer_rule(A, b)

if solution is not None:
  print("Solution for 3x3 system:", solution)
else:
  print("No unique solution for 3x3 system.")

Solution for 2x2 system: [ 2.15789474 -0.89473684]
Solution for 3x3 system: [1. 1. 2.]


In [ ]:
#9
import numpy as np

def gaussian_elimination(A, b):
  """Solves a system of linear equations using Gaussian elimination.

  Args:
    A: The coefficient matrix (NumPy array).
    b: The constant vector (NumPy array).

  Returns:
    A NumPy array containing the solutions, or None if no unique solution exists.
  """

  n = A.shape[0]  # Number of variables
  augmented_matrix = np.concatenate([A, b.reshape(n, 1)], axis=1)  # Augment A with b

  # Forward elimination (transform to upper triangular form)
  for i in range(n):
    pivot = augmented_matrix[i, i]  # Choose pivot element
    if pivot == 0:
      # If pivot is 0, try to find a row below with a non-zero element in the same column
      for j in range(i + 1, n):
        if augmented_matrix[j, i] != 0:
          augmented_matrix[[i, j]] = augmented_matrix[[j, i]]  # Swap rows
          pivot = augmented_matrix[i, i]
          break
      else:
        return None  # No unique solution (pivot is 0 and no suitable row found)

    # Eliminate elements below the pivot
    for j in range(i + 1, n):
      factor = augmented_matrix[j, i] / pivot
      augmented_matrix[j, :] = augmented_matrix[j, :] - factor * augmented_matrix[i, :]

  # Back substitution (solve for variables)
  solutions = np.zeros(n)
  for i in range(n - 1, -1, -1):
    solutions[i] = (augmented_matrix[i, -1] - np.dot(augmented_matrix[i, i + 1:n], solutions[i + 1:])) / augmented_matrix[i, i]

  return solutions

# Example usage:
A = np.array([[1, 2, -2], [2, 1, 1], [3, 2, 1]])
b = np.array([4, 0, 1])
solution = gaussian_elimination(A, b)

if solution is not None:
  print("Solution using Gaussian elimination:", solution)
else:
  print("No unique solution found.")

No unique solution found.


In [ ]:
#10
import numpy as np

def solve_by_matrix_inversion(A, b):
  """Solves a system of linear equations using matrix inversion.

  Args:
    A: The coefficient matrix (NumPy array).
    b: The constant vector (NumPy array).

  Returns:
    A NumPy array containing the solutions, or None if the matrix is singular.
  """

  try:
    A_inv = np.linalg.inv(A)  # Calculate the inverse of A
    solution = np.dot(A_inv, b)  # Multiply the inverse by b to get the solution
    return solution
  except np.linalg.LinAlgError:
    return None  # Matrix is singular (no inverse exists)

# Example usage:
A = np.array([[1, 2, 3], [0, 2, 3], [0, 0, 3]])
b = np.array([5, 4, 3])
solution = solve_by_matrix_inversion(A, b)

if solution is not None:
  print("Solution using matrix inversion:", solution)
else:
  print("No unique solution found (matrix is singular).")

Solution using matrix inversion: [1.  0.5 1. ]


Here’s a more **explained and simplified version** of your request, with clear explanations and steps for each problem. I’ve avoided complex notation like `frac`, `sqrt`, `abs`, etc., and used simple fractions and decimals where possible.

---

### 11. Vectors I
1. **Normalize Vector** $$ \mathbf{a} = [3, 4] $$:
   - The length of $$ \mathbf{a} $$ is calculated as:
     $$ |\mathbf{a}| = \sqrt{3^2 + 4^2} = 5 $$.
   - To make its length 1, divide each component by 5:
     $$ \mathbf{u_a} = [3/5, 4/5] $$.

2. **Length and Unit Vector of** $$ \mathbf{b} = [1, 1] $$:
   - Length: $$ |\mathbf{b}| = \sqrt{1^2 + 1^2} = \sqrt{2} $$.
   - Unit vector: $$ \mathbf{u_b} = [1/\sqrt{2}, 1/\sqrt{2}] $$.

3. **Length and Unit Vector of** $$ \mathbf{c} = [1, 2, 3] $$:
   - Length: $$ |\mathbf{c}| = \sqrt{1^2 + 2^2 + 3^2} = \sqrt{14} $$.
   - Unit vector: $$ \mathbf{u_c} = [1/\sqrt{14}, 2/\sqrt{14}, 3/\sqrt{14}] $$.

4. **Cartesian Coordinates of** $$ \mathbf{v} = [2, 3, 4] $$ in Basis $$ {\mathbf{b_1}, \mathbf{b_2}, \mathbf{b_3}} $$:
   - Solve the system: $$ \mathbf{v} = x\mathbf{b_1} + y\mathbf{b_2} + z\mathbf{b_3} $$.
   - Solution: $$ x = 3 $$, $$ y = 3 $$, $$ z = -1 $$.

---

### 12. Vectors II
1. **Add Vectors** $$ [2, 1] $$ and $$ [-1, 1] $$:
   - Sum: $$ [2 + (-1), 1 + 1] = [1, 2] $$.

2. **Area of Triangle Spanned by** $$ [2, 1, 2] $$ and $$ [-1, 1, 1] $$:
   - Cross product: $$ [2, 1, 2] \times [-1, 1, 1] = [-1, -4, 3] $$.
   - Area: $$ \frac{1}{2} \cdot \sqrt{(-1)^2 + (-4)^2 + 3^2} = \frac{\sqrt{26}}{2} $$.

3. **Volume of Parallelepiped Spanned by** $$ [2, 1, -1] $$, $$ [-1, 1, 0] $$, and $$ [1, 2, 1] $$:
   - Scalar triple product: $$ \text{det}([2, 1, -1], [-1, 1, 0], [1, 2, 1]) = 6 $$.
   - Volume: $$ 6 $$.

4. **Check Perpendicularity of** $$ [2, 1] $$ and $$ [-1, 1] $$:
   - Dot product: $$ 2(-1) + 1(1) = -1 $$ (not perpendicular).

5. **Angle Between** $$ [4, 2, 1] $$ and $$ [1, 3, 2] $$:
   - Dot product: $$ 4(1) + 2(3) + 1(2) = 12 $$.
   - Lengths: $$ |\mathbf{a}| = \sqrt{21} $$, $$ |\mathbf{b}| = \sqrt{14} $$.
   - Angle: $$ \cos^{-1}(12 / (\sqrt{21} \cdot \sqrt{14})) \approx 36.7^\circ $$.

6. **Prove Vector Identity**:
   - Expand both sides of $$ \mathbf{a} \times (\mathbf{b} \times \mathbf{c}) = (\mathbf{a} \cdot \mathbf{c})\mathbf{b} - (\mathbf{a} \cdot \mathbf{b})\mathbf{c} $$ using cross product rules.

---

### 13. Vectors III
1. **Divide Line Segment** from $$ A(-1, 2) $$ to $$ B(3, -2) $$ in Ratio $$ 1:3 $$:
   - Point: $$ P = \left(\frac{3(-1) + 1(3)}{4}, \frac{3(2) + 1(-2)}{4}\right) = (0, 1) $$.

2. **Project** $$ \mathbf{a} = (3, 4) $$ onto $$ OX $$ and $$ OY $$:
   - Projection onto $$ OX $$: $$ (3, 0) $$.
   - Projection onto $$ OY $$: $$ (0, 4) $$.

3. **Project** $$ \mathbf{a} = (2, 3) $$ onto $$ \mathbf{b} = (1, 1) $$:
   - Projection: $$ \frac{2(1) + 3(1)}{1^2 + 1^2} \cdot (1, 1) = \frac{5}{2}(1, 1) $$.

4. **Project** $$ \mathbf{b} = (1, 1) $$ onto $$ \mathbf{a} = (2, 3) $$:
   - Projection: $$ \frac{1(2) + 1(3)}{2^2 + 3^2} \cdot (2, 3) = \frac{5}{13}(2, 3) $$.

---

### 14. Equations of Lines on a Plane
1. **Line Through** $$ A(1, 2) $$ and $$ B(3, 4) $$:
   - Slope: $$ m = 1 $$.
   - Equation: $$ y = x + 1 $$.

2. **Line Through** $$ A(1, 2) $$ Parallel to $$ y = 2x + 3 $$:
   - Slope: $$ m = 2 $$.
   - Equation: $$ y = 2x $$.

3. **Line Through** $$ A(1, 2) $$ Perpendicular to $$ y = 2x + 3 $$:
   - Slope: $$ m = -1/2 $$.
   - Equation: $$ y = -1/2x + 5/2 $$.

4. **Intersection of** $$ y = 2x + 3 $$ and $$ y = 3x + 2 $$:
   - Solve: $$ 2x + 3 = 3x + 2 $$.
   - Intersection: $$ (1, 5) $$.

5. **Distance from** $$ A(1, 2) $$ to $$ y = 2x + 3 $$:
   - Distance: $$ \frac{|2(1) - 1(2) + 3|}{\sqrt{2^2 + (-1)^2}} = \frac{3}{\sqrt{5}} $$.

---

### 15. Equations of Second-Order Curves
1. **Circle with Center** $$ A(1, 2) $$ and Radius $$ r = 3 $$:
   - Equation: $$ (x-1)^2 + (y-2)^2 = 9 $$.

2. **Parabola Through** $$ x = 2 $$, $$ x = 4 $$, and $$ y(3) = 1 $$:
   - Equation: $$ y = a(x-2)(x-4) $$.
   - Solve for $$ a $$ using $$ y(3) = 1 $$.

3. **Center of Ellipse** $$ x^2 + 4y^2 - 4x - 16y + 16 = 0 $$:
   - Complete the square: $$ (x-2)^2 + 4(y-2)^2 = 4 $$.
   - Center: $$ (2, 2) $$.

---

### 16. Equations of Planes in Space
1. **Plane Through** $$ A(1, 2, 3) $$, $$ B(3, 4, 5) $$, and $$ C(2, 1, 4) $$:
   - Normal vector: $$ \mathbf{n} = \mathbf{AB} \times \mathbf{AC} $$.
   - Equation: $$ 2x - y - z + 1 = 0 $$.

2. **Plane Through** $$ A(1, 2, 3) $$ Parallel to $$ 2x + 3y + 4z = 5 $$:
   - Equation: $$ 2x + 3y + 4z = 20 $$.

3. **Distance from** $$ A(1, 2, 3) $$ to Plane $$ 2x + 3y + 4z = 5 $$:
   - Distance: $$ \frac{|2(1) + 3(2) + 4(3) - 5|}{\sqrt{2^2 + 3^2 + 4^2}} = \frac{13}{\sqrt{29}} $$.
---

### 17. Equations of Second-Order Surfaces
1. **Equation of a Sphere**:
   - Center at $$ P = (1, 2, 3) $$ and radius $$ r = 3 $$.
   - Equation: $$ (x-1)^2 + (y-2)^2 + (z-3)^2 = 9 $$.

2. **Common Points of Spheres**:
   - Spheres: $$ x^2 + y^2 + z^2 = 1 $$ and $$ x^2 + y^2 + z^2 = 2 $$.
   - No common points (one sphere is inside the other).

3. **Intersection of Spheres**:
   - Spheres: $$ x^2 + y^2 + z^2 = 1 $$ and $$ (x-1)^2 + y^2 + z^2 = 1 $$.
   - Intersection: Solve to find $$ x = 1/2 $$ and $$ y^2 + z^2 = 3/4 $$ (a circle).

4. **Tangent Plane to Paraboloid**:
   - Paraboloid: $$ z = (x-1)^2 + y^2 + 1 $$ at point $$ P(1, 0, 1) $$.
   - Tangent plane: $$ z = 1 $$.

---

### 18. Functions
1. **Plot Functions**:
   - $$ f(x) = x^2 $$, $$ g(x) = \sqrt{x} $$, $$ h(x) = 1/x $$, $$ j(x) = \sin(x) $$.
   - At $$ x = 2 $$:
     - $$ f(2) = 4 $$, $$ g(2) = \sqrt{2} $$, $$ h(2) = 0.5 $$, $$ j(2) = \sin(2) $$.

2. **Function Composition**:
   - Let $$ f(x) = 3x - 1 $$ and $$ g(x) = \sqrt{x} $$.
     - $$ f(g(x)) = 3\sqrt{x} - 1 $$.
     - $$ g(f(x)) = \sqrt{3x - 1} $$.
     - $$ f(f(x)) = 9x - 4 $$.
     - $$ g(g(x)) = \sqrt{\sqrt{x}} $$.

3. **Inverse Functions**:
   - For $$ f = {(1, 7), (2, 9), (3, 11)} $$, the inverse is $$ f^{-1} = {(7, 1), (9, 2), (11, 3)} $$.
   - For $$ f(x) = x - 1 $$, the inverse is $$ f^{-1}(x) = x + 1 $$.

---

### 19. Limits of Sequences
1. **Calculate Limits**:
   - $$ \lim_{n \to \infty} \frac{n^2 + 3n}{2n^2 - 2n} = \frac{1}{2} $$.
   - $$ \lim_{n \to \infty} \frac{(2n + 3)^3}{n^3 - 1} = 8 $$.

2. **Squeeze Theorem**:
   - Prove: $$ \lim_{n \to \infty} \frac{\sin(n)}{n} = 0 $$.

3. **Limit of Sequence**:
   - $$ a_n = \left(1 + \frac{1}{n}\right)^n $$.
   - Limit: $$ \lim_{n \to \infty} a_n = e $$.

---

### 20. Limits of Real Functions
1. **Compute Limits**:
   - $$ \lim_{x \to \infty} \frac{x^3 + 2x}{2x^4 - 3x^3} = 0 $$.
   - $$ \lim_{x \to 0} \frac{\sin(3x)}{2x + 1} = 0 $$.

2. **Asymptotes**:
   - For $$ f(x) = \frac{x^2 - 1}{x^2 + 1} $$, horizontal asymptote: $$ y = 1 $$.
   - For $$ g(x) = \frac{\sin(x)}{x^2 + 1} $$, horizontal asymptote: $$ y = 0 $$.

---

### 21. Derivatives

#### 1. \( y(x) = -3x + 3 \)
- **Derivative**: The derivative of a linear function \( y = mx + b \) is \( y' = m \).
- **Solution**: \( y'(x) = -3 \).

---

#### 2. \( y(x) = \pi x + \sin(1) \)
- **Derivative**: The derivative of \( \pi x \) is \( \pi \), and the derivative of a constant \( \sin(1) \) is \( 0 \).
- **Solution**: \( y'(x) = \pi \).

---

#### 3. \( y(x) = 4 + \sin(2) \)
- **Derivative**: Both \( 4 \) and \( \sin(2) \) are constants, so their derivatives are \( 0 \).
- **Solution**: \( y'(x) = 0 \).

---

#### 4. \( y(x) = 2x^3 - 3x^2 + 8x - 9 \)
- **Derivative**: Use the power rule \( \frac{d}{dx}(x^n) = nx^{n-1} \).
- **Solution**:
  \[
  y'(x) = 6x^2 - 6x + 8.
  \]

---

#### 5. \( y(x) = 6x^{1/3} \)
- **Derivative**: Use the power rule.
- **Solution**:
  \[
  y'(x) = 2x^{-2/3}.
  \]

---

#### 6. \( y(x) = \sqrt{x} \)
- **Rewrite**: \( \sqrt{x} = x^{1/2} \).
- **Derivative**: Use the power rule.
- **Solution**:
  \[
  y'(x) = \frac{1}{2\sqrt{x}}.
  \]

---

#### 7. \( y(x) = \cos(x) + \sin(x) \)
- **Derivative**: The derivative of \( \cos(x) \) is \( -\sin(x) \), and the derivative of \( \sin(x) \) is \( \cos(x) \).
- **Solution**:
  \[
  y'(x) = -\sin(x) + \cos(x).
  \]

---

#### 8. \( y(x) = 2\sin(x)\cos(x) \)
- **Simplify**: Use the identity \( 2\sin(x)\cos(x) = \sin(2x) \).
- **Derivative**: The derivative of \( \sin(2x) \) is \( 2\cos(2x) \).
- **Solution**:
  \[
  y'(x) = 2\cos(2x).
  \]

---

#### 9. \( y(x) = x\sin(x) \)
- **Derivative**: Use the product rule \( \frac{d}{dx}(uv) = u'v + uv' \), where \( u = x \) and \( v = \sin(x) \).
- **Solution**:
  \[
  y'(x) = \sin(x) + x\cos(x).
  \]

---

#### 10. \( y(x) = (x + 1)^2 \)
- **Expand**: \( (x + 1)^2 = x^2 + 2x + 1 \).
- **Derivative**: Use the power rule.
- **Solution**:
  \[
  y'(x) = 2(x + 1).
  \]

---

#### 11. \( y(x) = \frac{x}{x + 1} \)
- **Derivative**: Use the quotient rule \( \frac{d}{dx}\left(\frac{u}{v}\right) = \frac{u'v - uv'}{v^2} \), where \( u = x \) and \( v = x + 1 \).
- **Solution**:
  \[
  y'(x) = \frac{1}{(x + 1)^2}.
  \]

---

#### 12. \( y(x) = (x + 1)e^x \)
- **Derivative**: Use the product rule, where \( u = x + 1 \) and \( v = e^x \).
- **Solution**:
  \[
  y'(x) = e^x + (x + 1)e^x.
  \]

---

#### 13. \( y(x) = \sin(x^2) \)
- **Derivative**: Use the chain rule \( \frac{d}{dx}\sin(u) = \cos(u) \cdot u' \), where \( u = x^2 \).
- **Solution**:
  \[
  y'(x) = 2x\cos(x^2).
  \]

---

#### 14. \( y(x) = e^{-2x} \)
- **Derivative**: Use the chain rule, where \( u = -2x \).
- **Solution**:
  \[
  y'(x) = -2e^{-2x}.
  \]

---

#### 15. \( y(x) = \frac{1}{\sin(x + 1)} \)
- **Rewrite**: \( y(x) = \csc(x + 1) \).
- **Derivative**: The derivative of \( \csc(u) \) is \( -\csc(u)\cot(u) \cdot u' \), where \( u = x + 1 \).
- **Solution**:
  \[
  y'(x) = -\frac{\cos(x + 1)}{\sin^2(x + 1)}.
  \]

---

#### 16. \( y(x) = \sqrt{2x + 1} \)
- **Rewrite**: \( \sqrt{2x + 1} = (2x + 1)^{1/2} \).
- **Derivative**: Use the chain rule.
- **Solution**:
  \[
  y'(x) = \frac{1}{\sqrt{2x + 1}}.
  \]

---

#### 17. **Prove** \( \frac{d}{dx}(\ln(\sin(x))) = \cot(x) \)
- **Proof**:
  - Let \( y = \ln(\sin(x)) \).
  - Use the chain rule: \( y' = \frac{1}{\sin(x)} \cdot \cos(x) \).
  - Simplify: \( y' = \cot(x) \).

---

#### 18. **Verify** \( f''(x) = -f(x) \) for \( f(x) = \cos(x) \)
- **Proof**:
  - First derivative: \( f'(x) = -\sin(x) \).
  - Second derivative: \( f''(x) = -\cos(x) \).
  - Thus, \( f''(x) = -f(x) \).

---

#### 19. **Improper Limits Using L’Hôpital’s Rule**
1. \( \lim_{x \to 0} \frac{\sin(x)}{x} \):
   - Direct substitution gives \( \frac{0}{0} \).
   - Apply L’Hôpital’s Rule: \( \lim_{x \to 0} \frac{\cos(x)}{1} = 1 \).

2. \( \lim_{x \to \infty} \frac{\ln(x)}{x} \):
   - Direct substitution gives \( \frac{\infty}{\infty} \).
   - Apply L’Hôpital’s Rule: \( \lim_{x \to \infty} \frac{1/x}{1} = 0 \).

3. \( \lim_{x \to \infty} \frac{e^x}{x} \):
   - Direct substitution gives \( \frac{\infty}{\infty} \).
   - Apply L’Hôpital’s Rule: \( \lim_{x \to \infty} \frac{e^x}{1} = \infty \).

---

#### 20. **Velocity and Acceleration**
- Position function: \( x(t) = 3t^2 - 6t + 1 \).
- Velocity: \( V(t) = \frac{dx}{dt} = 6t - 6 \).
- Acceleration: \( a(t) = \frac{dV}{dt} = 6 \).
- At \( t = 2 \):
  - Velocity: \( V(2) = 6(2) - 6 = 6 \).
  - Acceleration: \( a(2) = 6 \).

---

Let me know if you need further clarification! 😊

### 22. Extremum
1. **Maximize Profit**:
   - Profit function: $$ P(u) = -2u^2 + 50u - 300 $$.
   - Derivative: $$ P'(u) = -4u + 50 $$.
   - Critical point: $$ u = 12.5 $$.

2. **Maximize Rectangle Area**:
   - With 10m string, dimensions: $$ 2.5m \times 2.5m $$.

3. **Find Extremum**:
   - For $$ f(x) = x^2 + 3x - 5 $$, derivative: $$ f'(x) = 2x + 3 $$.
   - Critical point: $$ x = -3/2 $$.

---

### 23. Taylor Series
1. **Taylor Series for** $$ f(x) = \cos(x) $$ around $$ x = 0 $$:
   - $$ \cos(x) \approx 1 - \frac{x^2}{2} + \frac{x^4}{24} $$.

2. **Taylor Series for** $$ h(x) = \frac{1}{1 - x} $$ around $$ x = 0 $$:
   - $$ \frac{1}{1 - x} \approx 1 + x + x^2 + x^3 $$.

3. **Tangent Line to** $$ f(x) = e^{\sin(x)} $$ at $$ x_0 = \pi $$:
   - Tangent line: $$ y = 1 $$.

---

### 24. Integrals
1. **Compute Integrals**:
   - $$ \int 1 \, dx = x + C $$.
   - $$ \int (x^2 + 2) \, dx = \frac{x^3}{3} + 2x + C $$.
   - $$ \int \sin(x) \, dx = -\cos(x) + C $$.

2. **Area Under Curve**:
   - For $$ f(x) = 2x + 1 $$ from $$ [0, \pi] $$:
     - Area: $$ \pi^2 + \pi $$.

3. **Length of Sine Curve**:
   - From $$ [0, \pi] $$:
     - Length: $$ \int_0^\pi \sqrt{1 + \cos^2(x)} \, dx $$.

---

### 25. Differential Equations
1. **Solve** $$ y'(x) = y $$:
   - Solution: $$ y(x) = Ce^x $$.

2. **Solve** $$ y''(x) + y'(x) = 0 $$ with $$ y(0) = 2 $$ and $$ y'(0) = -1 $$:
   - Solution: $$ y(x) = 2 - e^{-x} $$.

3. **Wave Equation**:
   - Check if $$ \psi(t, x) = A\cos(\omega t + kx) $$ satisfies:
     - $$ \frac{\partial^2 \psi}{\partial t^2} - v^2 \frac{\partial^2 \psi}{\partial x^2} = 0 $$